[launcher]
version = 1.0.0
description = This addon contains custom endpoints for downloading KV Store backups
author = Will Searle
[id]
version = 1.0.0
name = kv_downloader


[package]
id = kv_downloader
check_for_updates = false

[ui]
label = KV Store Backup Downloader
is_visible = true
