[script:kv_downloader]
match = /kv_downloader
script = kvbackup.py
handler = kvbackup.KVBackup
scripttype = persist
output_modes = json
passSystemAuth = false
requireAuthentication = true
passPayload = true
python.version = python3
